/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dao

import java.sql._
import anorm._
import com.mlasaf.dto._
import com.mlasaf.utils._
import org.apache.commons.dbcp._
import java.sql.Connection 
 
 

class Daos { 
  val algorithmColumnTypeDao : AlgorithmColumnTypeDao = new AlgorithmColumnTypeDao(); 
  val algorithmImplementationDao : AlgorithmImplementationDao = new AlgorithmImplementationDao(); 
  val algorithmOutputDao : AlgorithmOutputDao = new AlgorithmOutputDao(); 
  val algorithmOutputTypeDao : AlgorithmOutputTypeDao = new AlgorithmOutputTypeDao(); 
  val algorithmParamDao : AlgorithmParamDao = new AlgorithmParamDao(); 
  val algorithmParamTypeDao : AlgorithmParamTypeDao = new AlgorithmParamTypeDao(); 
  val algorithmRunDao : AlgorithmRunDao = new AlgorithmRunDao(); 
  val algorithmRunTypeDao : AlgorithmRunTypeDao = new AlgorithmRunTypeDao(); 
  val algorithmRunViewDao : AlgorithmRunViewDao = new AlgorithmRunViewDao(); 
  val algorithmScheduleDao : AlgorithmScheduleDao = new AlgorithmScheduleDao(); 
  val algorithmScheduleColumnDao : AlgorithmScheduleColumnDao = new AlgorithmScheduleColumnDao(); 
  val algorithmScheduleParamDao : AlgorithmScheduleParamDao = new AlgorithmScheduleParamDao(); 
  val algorithmScheduleTypeDao : AlgorithmScheduleTypeDao = new AlgorithmScheduleTypeDao(); 
  val algorithmScheduleViewDao : AlgorithmScheduleViewDao = new AlgorithmScheduleViewDao(); 
  val algorithmScheduleViewTypeDao : AlgorithmScheduleViewTypeDao = new AlgorithmScheduleViewTypeDao(); 
  val algorithmStorageSupportDao : AlgorithmStorageSupportDao = new AlgorithmStorageSupportDao(); 
  val algorithmTypeDao : AlgorithmTypeDao = new AlgorithmTypeDao(); 
  val algorithmTypeColumnTypeDao : AlgorithmTypeColumnTypeDao = new AlgorithmTypeColumnTypeDao(); 
  val algorithmTypeOutputTypeDao : AlgorithmTypeOutputTypeDao = new AlgorithmTypeOutputTypeDao(); 
  val algorithmTypeVersionDao : AlgorithmTypeVersionDao = new AlgorithmTypeVersionDao(); 
  val executorContextDao : ExecutorContextDao = new ExecutorContextDao(); 
  val executorContextRuntimeDao : ExecutorContextRuntimeDao = new ExecutorContextRuntimeDao(); 
  val executorHostDao : ExecutorHostDao = new ExecutorHostDao(); 
  val executorInstanceDao : ExecutorInstanceDao = new ExecutorInstanceDao(); 
  val executorInstanceStateDao : ExecutorInstanceStateDao = new ExecutorInstanceStateDao(); 
  val executorRestDao : ExecutorRestDao = new ExecutorRestDao(); 
  val executorRestCallDao : ExecutorRestCallDao = new ExecutorRestCallDao(); 
  val executorStorageDao : ExecutorStorageDao = new ExecutorStorageDao(); 
  val executorStorageSnapshotDao : ExecutorStorageSnapshotDao = new ExecutorStorageSnapshotDao(); 
  val executorStorageTypeDao : ExecutorStorageTypeDao = new ExecutorStorageTypeDao(); 
  val executorStorageViewDao : ExecutorStorageViewDao = new ExecutorStorageViewDao(); 
  val executorTypeDao : ExecutorTypeDao = new ExecutorTypeDao(); 
  val resourceManagerDao : ResourceManagerDao = new ResourceManagerDao(); 
  val resourceManagerAllocationDao : ResourceManagerAllocationDao = new ResourceManagerAllocationDao(); 
  val resourceManagerCheckDao : ResourceManagerCheckDao = new ResourceManagerCheckDao(); 
  val resourceManagerMeasureDao : ResourceManagerMeasureDao = new ResourceManagerMeasureDao(); 
  val resourceManagerTypeDao : ResourceManagerTypeDao = new ResourceManagerTypeDao(); 
  val resourceMeasureDao : ResourceMeasureDao = new ResourceMeasureDao(); 
  val sourceDownloadDao : SourceDownloadDao = new SourceDownloadDao(); 
  val sourceDownloadStatDao : SourceDownloadStatDao = new SourceDownloadStatDao(); 
  val sourceDownloadStatColumnDao : SourceDownloadStatColumnDao = new SourceDownloadStatColumnDao(); 
  val sourceInstanceDao : SourceInstanceDao = new SourceInstanceDao(); 
  val sourceParamDao : SourceParamDao = new SourceParamDao(); 
  val sourceParamValueDao : SourceParamValueDao = new SourceParamValueDao(); 
  val sourceScheduleDao : SourceScheduleDao = new SourceScheduleDao(); 
  val sourceTypeDao : SourceTypeDao = new SourceTypeDao(); 
  val sourceTypeParamDao : SourceTypeParamDao = new SourceTypeParamDao(); 
  val sourceViewDao : SourceViewDao = new SourceViewDao(); 
  val sourceViewColumnDao : SourceViewColumnDao = new SourceViewColumnDao(); 
  val sourceViewTypeDao : SourceViewTypeDao = new SourceViewTypeDao(); 
  val vAlgorithmColumnTypeSummaryDao : VAlgorithmColumnTypeSummaryDao = new VAlgorithmColumnTypeSummaryDao(); 
  val vAlgorithmImplementationDao : VAlgorithmImplementationDao = new VAlgorithmImplementationDao(); 
  val vAlgorithmImplementationSummaryDao : VAlgorithmImplementationSummaryDao = new VAlgorithmImplementationSummaryDao(); 
  val vAlgorithmOutputDao : VAlgorithmOutputDao = new VAlgorithmOutputDao(); 
  val vAlgorithmOutputTypeSummaryDao : VAlgorithmOutputTypeSummaryDao = new VAlgorithmOutputTypeSummaryDao(); 
  val vAlgorithmParamSummaryDao : VAlgorithmParamSummaryDao = new VAlgorithmParamSummaryDao(); 
  val vAlgorithmParamTypeDao : VAlgorithmParamTypeDao = new VAlgorithmParamTypeDao(); 
  val vAlgorithmRunDao : VAlgorithmRunDao = new VAlgorithmRunDao(); 
  val vAlgorithmRunSummaryDao : VAlgorithmRunSummaryDao = new VAlgorithmRunSummaryDao(); 
  val vAlgorithmRunTypeSummaryDao : VAlgorithmRunTypeSummaryDao = new VAlgorithmRunTypeSummaryDao(); 
  val vAlgorithmRunViewDao : VAlgorithmRunViewDao = new VAlgorithmRunViewDao(); 
  val vAlgorithmScheduleDao : VAlgorithmScheduleDao = new VAlgorithmScheduleDao(); 
  val vAlgorithmScheduleColumnDao : VAlgorithmScheduleColumnDao = new VAlgorithmScheduleColumnDao(); 
  val vAlgorithmScheduleParamDao : VAlgorithmScheduleParamDao = new VAlgorithmScheduleParamDao(); 
  val vAlgorithmScheduleSummaryDao : VAlgorithmScheduleSummaryDao = new VAlgorithmScheduleSummaryDao(); 
  val vAlgorithmScheduleTypeSummaryDao : VAlgorithmScheduleTypeSummaryDao = new VAlgorithmScheduleTypeSummaryDao(); 
  val vAlgorithmScheduleViewDao : VAlgorithmScheduleViewDao = new VAlgorithmScheduleViewDao(); 
  val vAlgorithmScheduleViewSummaryDao : VAlgorithmScheduleViewSummaryDao = new VAlgorithmScheduleViewSummaryDao(); 
  val vAlgorithmScheduleViewTypeSummaryDao : VAlgorithmScheduleViewTypeSummaryDao = new VAlgorithmScheduleViewTypeSummaryDao(); 
  val vAlgorithmStorageSupportDao : VAlgorithmStorageSupportDao = new VAlgorithmStorageSupportDao(); 
  val vAlgorithmTypeColumnTypeDao : VAlgorithmTypeColumnTypeDao = new VAlgorithmTypeColumnTypeDao(); 
  val vAlgorithmTypeOutputTypeDao : VAlgorithmTypeOutputTypeDao = new VAlgorithmTypeOutputTypeDao(); 
  val vAlgorithmTypeSummaryDao : VAlgorithmTypeSummaryDao = new VAlgorithmTypeSummaryDao(); 
  val vAlgorithmTypeVersionDao : VAlgorithmTypeVersionDao = new VAlgorithmTypeVersionDao(); 
  val vAlgorithmTypeVersionSummaryDao : VAlgorithmTypeVersionSummaryDao = new VAlgorithmTypeVersionSummaryDao(); 
  val vExecutorContextDao : VExecutorContextDao = new VExecutorContextDao(); 
  val vExecutorContextRuntimeDao : VExecutorContextRuntimeDao = new VExecutorContextRuntimeDao(); 
  val vExecutorContextSummaryDao : VExecutorContextSummaryDao = new VExecutorContextSummaryDao(); 
  val vExecutorHostSummaryDao : VExecutorHostSummaryDao = new VExecutorHostSummaryDao(); 
  val vExecutorInstanceDao : VExecutorInstanceDao = new VExecutorInstanceDao(); 
  val vExecutorInstanceStateDao : VExecutorInstanceStateDao = new VExecutorInstanceStateDao(); 
  val vExecutorInstanceSummaryDao : VExecutorInstanceSummaryDao = new VExecutorInstanceSummaryDao(); 
  val vExecutorRestDao : VExecutorRestDao = new VExecutorRestDao(); 
  val vExecutorRestCallDao : VExecutorRestCallDao = new VExecutorRestCallDao(); 
  val vExecutorRestSummaryDao : VExecutorRestSummaryDao = new VExecutorRestSummaryDao(); 
  val vExecutorStorageDao : VExecutorStorageDao = new VExecutorStorageDao(); 
  val vExecutorStorageSnapshotDao : VExecutorStorageSnapshotDao = new VExecutorStorageSnapshotDao(); 
  val vExecutorStorageSnapshotSummaryDao : VExecutorStorageSnapshotSummaryDao = new VExecutorStorageSnapshotSummaryDao(); 
  val vExecutorStorageSummaryDao : VExecutorStorageSummaryDao = new VExecutorStorageSummaryDao(); 
  val vExecutorStorageTypeSummaryDao : VExecutorStorageTypeSummaryDao = new VExecutorStorageTypeSummaryDao(); 
  val vExecutorStorageViewDao : VExecutorStorageViewDao = new VExecutorStorageViewDao(); 
  val vExecutorStorageViewSummaryDao : VExecutorStorageViewSummaryDao = new VExecutorStorageViewSummaryDao(); 
  val vExecutorTypeSummaryDao : VExecutorTypeSummaryDao = new VExecutorTypeSummaryDao(); 
  val vResourceManagerDao : VResourceManagerDao = new VResourceManagerDao(); 
  val vResourceManagerAllocationDao : VResourceManagerAllocationDao = new VResourceManagerAllocationDao(); 
  val vResourceManagerCheckDao : VResourceManagerCheckDao = new VResourceManagerCheckDao(); 
  val vResourceManagerMeasureDao : VResourceManagerMeasureDao = new VResourceManagerMeasureDao(); 
  val vResourceManagerSummaryDao : VResourceManagerSummaryDao = new VResourceManagerSummaryDao(); 
  val vResourceManagerTypeSummaryDao : VResourceManagerTypeSummaryDao = new VResourceManagerTypeSummaryDao(); 
  val vResourceMeasureSummaryDao : VResourceMeasureSummaryDao = new VResourceMeasureSummaryDao(); 
  val vSourceDownloadDao : VSourceDownloadDao = new VSourceDownloadDao(); 
  val vSourceDownloadStatDao : VSourceDownloadStatDao = new VSourceDownloadStatDao(); 
  val vSourceDownloadStatColumnDao : VSourceDownloadStatColumnDao = new VSourceDownloadStatColumnDao(); 
  val vSourceDownloadSummaryDao : VSourceDownloadSummaryDao = new VSourceDownloadSummaryDao(); 
  val vSourceInstanceDao : VSourceInstanceDao = new VSourceInstanceDao(); 
  val vSourceInstanceSummaryDao : VSourceInstanceSummaryDao = new VSourceInstanceSummaryDao(); 
  val vSourceParamSummaryDao : VSourceParamSummaryDao = new VSourceParamSummaryDao(); 
  val vSourceParamValueDao : VSourceParamValueDao = new VSourceParamValueDao(); 
  val vSourceScheduleDao : VSourceScheduleDao = new VSourceScheduleDao(); 
  val vSourceScheduleSummaryDao : VSourceScheduleSummaryDao = new VSourceScheduleSummaryDao(); 
  val vSourceTypeParamDao : VSourceTypeParamDao = new VSourceTypeParamDao(); 
  val vSourceTypeSummaryDao : VSourceTypeSummaryDao = new VSourceTypeSummaryDao(); 
  val vSourceViewDao : VSourceViewDao = new VSourceViewDao(); 
  val vSourceViewColumnDao : VSourceViewColumnDao = new VSourceViewColumnDao(); 
  val vSourceViewColumnSummaryDao : VSourceViewColumnSummaryDao = new VSourceViewColumnSummaryDao(); 
  val vSourceViewSummaryDao : VSourceViewSummaryDao = new VSourceViewSummaryDao(); 
  val vSourceViewTypeSummaryDao : VSourceViewTypeSummaryDao = new VSourceViewTypeSummaryDao(); 
  def initialize(daoConn : DaoConnection ): Unit = { 
    algorithmColumnTypeDao.initialize(daoConn) 
    algorithmImplementationDao.initialize(daoConn) 
    algorithmOutputDao.initialize(daoConn) 
    algorithmOutputTypeDao.initialize(daoConn) 
    algorithmParamDao.initialize(daoConn) 
    algorithmParamTypeDao.initialize(daoConn) 
    algorithmRunDao.initialize(daoConn) 
    algorithmRunTypeDao.initialize(daoConn) 
    algorithmRunViewDao.initialize(daoConn) 
    algorithmScheduleDao.initialize(daoConn) 
    algorithmScheduleColumnDao.initialize(daoConn) 
    algorithmScheduleParamDao.initialize(daoConn) 
    algorithmScheduleTypeDao.initialize(daoConn) 
    algorithmScheduleViewDao.initialize(daoConn) 
    algorithmScheduleViewTypeDao.initialize(daoConn) 
    algorithmStorageSupportDao.initialize(daoConn) 
    algorithmTypeDao.initialize(daoConn) 
    algorithmTypeColumnTypeDao.initialize(daoConn) 
    algorithmTypeOutputTypeDao.initialize(daoConn) 
    algorithmTypeVersionDao.initialize(daoConn) 
    executorContextDao.initialize(daoConn) 
    executorContextRuntimeDao.initialize(daoConn) 
    executorHostDao.initialize(daoConn) 
    executorInstanceDao.initialize(daoConn) 
    executorInstanceStateDao.initialize(daoConn) 
    executorRestDao.initialize(daoConn) 
    executorRestCallDao.initialize(daoConn) 
    executorStorageDao.initialize(daoConn) 
    executorStorageSnapshotDao.initialize(daoConn) 
    executorStorageTypeDao.initialize(daoConn) 
    executorStorageViewDao.initialize(daoConn) 
    executorTypeDao.initialize(daoConn) 
    resourceManagerDao.initialize(daoConn) 
    resourceManagerAllocationDao.initialize(daoConn) 
    resourceManagerCheckDao.initialize(daoConn) 
    resourceManagerMeasureDao.initialize(daoConn) 
    resourceManagerTypeDao.initialize(daoConn) 
    resourceMeasureDao.initialize(daoConn) 
    sourceDownloadDao.initialize(daoConn) 
    sourceDownloadStatDao.initialize(daoConn) 
    sourceDownloadStatColumnDao.initialize(daoConn) 
    sourceInstanceDao.initialize(daoConn) 
    sourceParamDao.initialize(daoConn) 
    sourceParamValueDao.initialize(daoConn) 
    sourceScheduleDao.initialize(daoConn) 
    sourceTypeDao.initialize(daoConn) 
    sourceTypeParamDao.initialize(daoConn) 
    sourceViewDao.initialize(daoConn) 
    sourceViewColumnDao.initialize(daoConn) 
    sourceViewTypeDao.initialize(daoConn) 
    vAlgorithmColumnTypeSummaryDao.initialize(daoConn) 
    vAlgorithmImplementationDao.initialize(daoConn) 
    vAlgorithmImplementationSummaryDao.initialize(daoConn) 
    vAlgorithmOutputDao.initialize(daoConn) 
    vAlgorithmOutputTypeSummaryDao.initialize(daoConn) 
    vAlgorithmParamSummaryDao.initialize(daoConn) 
    vAlgorithmParamTypeDao.initialize(daoConn) 
    vAlgorithmRunDao.initialize(daoConn) 
    vAlgorithmRunSummaryDao.initialize(daoConn) 
    vAlgorithmRunTypeSummaryDao.initialize(daoConn) 
    vAlgorithmRunViewDao.initialize(daoConn) 
    vAlgorithmScheduleDao.initialize(daoConn) 
    vAlgorithmScheduleColumnDao.initialize(daoConn) 
    vAlgorithmScheduleParamDao.initialize(daoConn) 
    vAlgorithmScheduleSummaryDao.initialize(daoConn) 
    vAlgorithmScheduleTypeSummaryDao.initialize(daoConn) 
    vAlgorithmScheduleViewDao.initialize(daoConn) 
    vAlgorithmScheduleViewSummaryDao.initialize(daoConn) 
    vAlgorithmScheduleViewTypeSummaryDao.initialize(daoConn) 
    vAlgorithmStorageSupportDao.initialize(daoConn) 
    vAlgorithmTypeColumnTypeDao.initialize(daoConn) 
    vAlgorithmTypeOutputTypeDao.initialize(daoConn) 
    vAlgorithmTypeSummaryDao.initialize(daoConn) 
    vAlgorithmTypeVersionDao.initialize(daoConn) 
    vAlgorithmTypeVersionSummaryDao.initialize(daoConn) 
    vExecutorContextDao.initialize(daoConn) 
    vExecutorContextRuntimeDao.initialize(daoConn) 
    vExecutorContextSummaryDao.initialize(daoConn) 
    vExecutorHostSummaryDao.initialize(daoConn) 
    vExecutorInstanceDao.initialize(daoConn) 
    vExecutorInstanceStateDao.initialize(daoConn) 
    vExecutorInstanceSummaryDao.initialize(daoConn) 
    vExecutorRestDao.initialize(daoConn) 
    vExecutorRestCallDao.initialize(daoConn) 
    vExecutorRestSummaryDao.initialize(daoConn) 
    vExecutorStorageDao.initialize(daoConn) 
    vExecutorStorageSnapshotDao.initialize(daoConn) 
    vExecutorStorageSnapshotSummaryDao.initialize(daoConn) 
    vExecutorStorageSummaryDao.initialize(daoConn) 
    vExecutorStorageTypeSummaryDao.initialize(daoConn) 
    vExecutorStorageViewDao.initialize(daoConn) 
    vExecutorStorageViewSummaryDao.initialize(daoConn) 
    vExecutorTypeSummaryDao.initialize(daoConn) 
    vResourceManagerDao.initialize(daoConn) 
    vResourceManagerAllocationDao.initialize(daoConn) 
    vResourceManagerCheckDao.initialize(daoConn) 
    vResourceManagerMeasureDao.initialize(daoConn) 
    vResourceManagerSummaryDao.initialize(daoConn) 
    vResourceManagerTypeSummaryDao.initialize(daoConn) 
    vResourceMeasureSummaryDao.initialize(daoConn) 
    vSourceDownloadDao.initialize(daoConn) 
    vSourceDownloadStatDao.initialize(daoConn) 
    vSourceDownloadStatColumnDao.initialize(daoConn) 
    vSourceDownloadSummaryDao.initialize(daoConn) 
    vSourceInstanceDao.initialize(daoConn) 
    vSourceInstanceSummaryDao.initialize(daoConn) 
    vSourceParamSummaryDao.initialize(daoConn) 
    vSourceParamValueDao.initialize(daoConn) 
    vSourceScheduleDao.initialize(daoConn) 
    vSourceScheduleSummaryDao.initialize(daoConn) 
    vSourceTypeParamDao.initialize(daoConn) 
    vSourceTypeSummaryDao.initialize(daoConn) 
    vSourceViewDao.initialize(daoConn) 
    vSourceViewColumnDao.initialize(daoConn) 
    vSourceViewColumnSummaryDao.initialize(daoConn) 
    vSourceViewSummaryDao.initialize(daoConn) 
    vSourceViewTypeSummaryDao.initialize(daoConn) 
  } 
} 
 
