/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VAlgorithmOutputDto ( 
     val algorithmOutputId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val algorithmRunId : Long
     , val algorithmOutputTypeId : Long
     , val executorStorageViewId : Long
     , val outputPath : String
     , val algorithmOutputType_algorithmOutputTypeId : Long
     , val algorithmOutputType_guid : Long
     , val algorithmOutputType_insertedRowDate : java.util.Date
     , val algorithmOutputType_lastUpdatedDate : java.util.Date
     , val algorithmOutputType_algorithmOutputTypeName : String
     , val executorStorageView_executorStorageViewId : Long
     , val executorStorageView_guid : Long
     , val executorStorageView_insertedRowDate : java.util.Date
     , val executorStorageView_lastUpdatedDate : java.util.Date
     , val executorStorageView_executorStorageSnapshotId : Long
     , val executorStorageView_executorStorageId : Long
     , val executorStorageView_sourceDownloadId : Long
     , val executorStorageView_sourceViewId : Long
     , val executorStorageView_storagePath : String
     , val executorStorageView_viewSize : Long
     , val executorStorageView_viewRowsCount : Long
     , val executorStorageView_isValid : Int 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vAlgorithmOutput";    }  
   def fields : String = {    "algorithmOutputId,guid,insertedRowDate,lastUpdatedDate,algorithmRunId,algorithmOutputTypeId,executorStorageViewId,outputPath,algorithmOutputType_algorithmOutputTypeId,algorithmOutputType_guid,algorithmOutputType_insertedRowDate,algorithmOutputType_lastUpdatedDate,algorithmOutputType_algorithmOutputTypeName,executorStorageView_executorStorageViewId,executorStorageView_guid,executorStorageView_insertedRowDate,executorStorageView_lastUpdatedDate,executorStorageView_executorStorageSnapshotId,executorStorageView_executorStorageId,executorStorageView_sourceDownloadId,executorStorageView_sourceViewId,executorStorageView_storagePath,executorStorageView_viewSize,executorStorageView_viewRowsCount,executorStorageView_isValid";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    algorithmOutputId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(algorithmOutputId,guid,insertedRowDate,lastUpdatedDate,algorithmRunId,algorithmOutputTypeId,executorStorageViewId,outputPath,algorithmOutputType_algorithmOutputTypeId,algorithmOutputType_guid,algorithmOutputType_insertedRowDate,algorithmOutputType_lastUpdatedDate,algorithmOutputType_algorithmOutputTypeName,executorStorageView_executorStorageViewId,executorStorageView_guid,executorStorageView_insertedRowDate,executorStorageView_lastUpdatedDate,executorStorageView_executorStorageSnapshotId,executorStorageView_executorStorageId,executorStorageView_sourceDownloadId,executorStorageView_sourceViewId,executorStorageView_storagePath,executorStorageView_viewSize,executorStorageView_viewRowsCount,executorStorageView_isValid)  }  
 def toStringArray() : Array[String] = {    Array(""+algorithmOutputId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+algorithmRunId,""+algorithmOutputTypeId,""+executorStorageViewId,""+outputPath,""+algorithmOutputType_algorithmOutputTypeId,""+algorithmOutputType_guid,""+algorithmOutputType_insertedRowDate,""+algorithmOutputType_lastUpdatedDate,""+algorithmOutputType_algorithmOutputTypeName,""+executorStorageView_executorStorageViewId,""+executorStorageView_guid,""+executorStorageView_insertedRowDate,""+executorStorageView_lastUpdatedDate,""+executorStorageView_executorStorageSnapshotId,""+executorStorageView_executorStorageId,""+executorStorageView_sourceDownloadId,""+executorStorageView_sourceViewId,""+executorStorageView_storagePath,""+executorStorageView_viewSize,""+executorStorageView_viewRowsCount,""+executorStorageView_isValid)   }  
 def toFullString() : String = {    "algorithmOutputId:'"+algorithmOutputId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"algorithmRunId:'"+algorithmRunId+"'"+","+"algorithmOutputTypeId:'"+algorithmOutputTypeId+"'"+","+"executorStorageViewId:'"+executorStorageViewId+"'"+","+"outputPath:'"+outputPath+"'"+","+"algorithmOutputType_algorithmOutputTypeId:'"+algorithmOutputType_algorithmOutputTypeId+"'"+","+"algorithmOutputType_guid:'"+algorithmOutputType_guid+"'"+","+"algorithmOutputType_insertedRowDate:'"+algorithmOutputType_insertedRowDate+"'"+","+"algorithmOutputType_lastUpdatedDate:'"+algorithmOutputType_lastUpdatedDate+"'"+","+"algorithmOutputType_algorithmOutputTypeName:'"+algorithmOutputType_algorithmOutputTypeName+"'"+","+"executorStorageView_executorStorageViewId:'"+executorStorageView_executorStorageViewId+"'"+","+"executorStorageView_guid:'"+executorStorageView_guid+"'"+","+"executorStorageView_insertedRowDate:'"+executorStorageView_insertedRowDate+"'"+","+"executorStorageView_lastUpdatedDate:'"+executorStorageView_lastUpdatedDate+"'"+","+"executorStorageView_executorStorageSnapshotId:'"+executorStorageView_executorStorageSnapshotId+"'"+","+"executorStorageView_executorStorageId:'"+executorStorageView_executorStorageId+"'"+","+"executorStorageView_sourceDownloadId:'"+executorStorageView_sourceDownloadId+"'"+","+"executorStorageView_sourceViewId:'"+executorStorageView_sourceViewId+"'"+","+"executorStorageView_storagePath:'"+executorStorageView_storagePath+"'"+","+"executorStorageView_viewSize:'"+executorStorageView_viewSize+"'"+","+"executorStorageView_viewRowsCount:'"+executorStorageView_viewRowsCount+"'"+","+"executorStorageView_isValid:'"+executorStorageView_isValid+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "algorithmOutputId" => algorithmOutputId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "algorithmRunId" => algorithmRunId  
     case "algorithmOutputTypeId" => algorithmOutputTypeId  
     case "executorStorageViewId" => executorStorageViewId  
     case "outputPath" => outputPath  
     case "algorithmOutputType_algorithmOutputTypeId" => algorithmOutputType_algorithmOutputTypeId  
     case "algorithmOutputType_guid" => algorithmOutputType_guid  
     case "algorithmOutputType_insertedRowDate" => algorithmOutputType_insertedRowDate  
     case "algorithmOutputType_lastUpdatedDate" => algorithmOutputType_lastUpdatedDate  
     case "algorithmOutputType_algorithmOutputTypeName" => algorithmOutputType_algorithmOutputTypeName  
     case "executorStorageView_executorStorageViewId" => executorStorageView_executorStorageViewId  
     case "executorStorageView_guid" => executorStorageView_guid  
     case "executorStorageView_insertedRowDate" => executorStorageView_insertedRowDate  
     case "executorStorageView_lastUpdatedDate" => executorStorageView_lastUpdatedDate  
     case "executorStorageView_executorStorageSnapshotId" => executorStorageView_executorStorageSnapshotId  
     case "executorStorageView_executorStorageId" => executorStorageView_executorStorageId  
     case "executorStorageView_sourceDownloadId" => executorStorageView_sourceDownloadId  
     case "executorStorageView_sourceViewId" => executorStorageView_sourceViewId  
     case "executorStorageView_storagePath" => executorStorageView_storagePath  
     case "executorStorageView_viewSize" => executorStorageView_viewSize  
     case "executorStorageView_viewRowsCount" => executorStorageView_viewRowsCount  
     case "executorStorageView_isValid" => executorStorageView_isValid   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "algorithmOutputId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "algorithmRunId" => "Long"  
     case "algorithmOutputTypeId" => "Long"  
     case "executorStorageViewId" => "Long"  
     case "outputPath" => "String"  
     case "algorithmOutputType_algorithmOutputTypeId" => "Long"  
     case "algorithmOutputType_guid" => "Long"  
     case "algorithmOutputType_insertedRowDate" => "java.util.Date"  
     case "algorithmOutputType_lastUpdatedDate" => "java.util.Date"  
     case "algorithmOutputType_algorithmOutputTypeName" => "String"  
     case "executorStorageView_executorStorageViewId" => "Long"  
     case "executorStorageView_guid" => "Long"  
     case "executorStorageView_insertedRowDate" => "java.util.Date"  
     case "executorStorageView_lastUpdatedDate" => "java.util.Date"  
     case "executorStorageView_executorStorageSnapshotId" => "Long"  
     case "executorStorageView_executorStorageId" => "Long"  
     case "executorStorageView_sourceDownloadId" => "Long"  
     case "executorStorageView_sourceViewId" => "Long"  
     case "executorStorageView_storagePath" => "String"  
     case "executorStorageView_viewSize" => "Long"  
     case "executorStorageView_viewRowsCount" => "Long"  
     case "executorStorageView_isValid" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VAlgorithmOutputDto { 
  val TABLE_NAME = "vAlgorithmOutput"; 
   val FIELD_algorithmOutputId = "algorithmOutputId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_algorithmRunId = "algorithmRunId";
   val FIELD_algorithmOutputTypeId = "algorithmOutputTypeId";
   val FIELD_executorStorageViewId = "executorStorageViewId";
   val FIELD_outputPath = "outputPath";
   val FIELD_algorithmOutputType_algorithmOutputTypeId = "algorithmOutputType_algorithmOutputTypeId";
   val FIELD_algorithmOutputType_guid = "algorithmOutputType_guid";
   val FIELD_algorithmOutputType_insertedRowDate = "algorithmOutputType_insertedRowDate";
   val FIELD_algorithmOutputType_lastUpdatedDate = "algorithmOutputType_lastUpdatedDate";
   val FIELD_algorithmOutputType_algorithmOutputTypeName = "algorithmOutputType_algorithmOutputTypeName";
   val FIELD_executorStorageView_executorStorageViewId = "executorStorageView_executorStorageViewId";
   val FIELD_executorStorageView_guid = "executorStorageView_guid";
   val FIELD_executorStorageView_insertedRowDate = "executorStorageView_insertedRowDate";
   val FIELD_executorStorageView_lastUpdatedDate = "executorStorageView_lastUpdatedDate";
   val FIELD_executorStorageView_executorStorageSnapshotId = "executorStorageView_executorStorageSnapshotId";
   val FIELD_executorStorageView_executorStorageId = "executorStorageView_executorStorageId";
   val FIELD_executorStorageView_sourceDownloadId = "executorStorageView_sourceDownloadId";
   val FIELD_executorStorageView_sourceViewId = "executorStorageView_sourceViewId";
   val FIELD_executorStorageView_storagePath = "executorStorageView_storagePath";
   val FIELD_executorStorageView_viewSize = "executorStorageView_viewSize";
   val FIELD_executorStorageView_viewRowsCount = "executorStorageView_viewRowsCount";
   val FIELD_executorStorageView_isValid = "executorStorageView_isValid";

}

 
