/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VAlgorithmImplementationDto ( 
     val algorithmImplementationId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val algorithmTypeVersionId : Long
     , val executorTypeId : Long
     , val algorithmImplementationName : String
     , val algorithmImplementationClass : String
     , val algorithmTypeVersion_algorithmTypeVersionId : Long
     , val algorithmTypeVersion_insertedRowDate : java.util.Date
     , val algorithmTypeVersion_lastUpdatedDate : java.util.Date
     , val algorithmTypeVersion_guid : Long
     , val algorithmTypeVersion_algorithmTypeId : Long
     , val algorithmTypeVersion_algorithmTypeVersionName : String
     , val executorType_executorTypeId : Long
     , val executorType_guid : Long
     , val executorType_insertedRowDate : java.util.Date
     , val executorType_lastUpdatedDate : java.util.Date
     , val executorType_executorTypeName : String
     , val executorType_executorTypeClass : String 
     ) extends BaseReadOnlyDto {  
   def tableName : String = { 
   "vAlgorithmImplementation"; 
   }  
   def fields : String = { 
   "algorithmImplementationId,guid,insertedRowDate,lastUpdatedDate,algorithmTypeVersionId,executorTypeId,algorithmImplementationName,algorithmImplementationClass,algorithmTypeVersion_algorithmTypeVersionId,algorithmTypeVersion_insertedRowDate,algorithmTypeVersion_lastUpdatedDate,algorithmTypeVersion_guid,algorithmTypeVersion_algorithmTypeId,algorithmTypeVersion_algorithmTypeVersionName,executorType_executorTypeId,executorType_guid,executorType_insertedRowDate,executorType_lastUpdatedDate,executorType_executorTypeName,executorType_executorTypeClass"; 
   }  
   def pkFields : String = { 
   ""; 
   }  
   def fkFields : String = { 
   ""; 
   }  
   def nameField : String = { 
   ""; 
   }  
 def getPk() : Long = {
    algorithmImplementationId
  }  
 def getInsertedRowDate() : java.util.Date = {
    insertedRowDate
  }  
 def getLastUpdatedDate() : java.util.Date = {
    lastUpdatedDate
  }  
 def getGuid() : Long = {
    guid
  }  
 def toAnyArray() : Array[Any] = {
    Array(algorithmImplementationId,guid,insertedRowDate,lastUpdatedDate,algorithmTypeVersionId,executorTypeId,algorithmImplementationName,algorithmImplementationClass,algorithmTypeVersion_algorithmTypeVersionId,algorithmTypeVersion_insertedRowDate,algorithmTypeVersion_lastUpdatedDate,algorithmTypeVersion_guid,algorithmTypeVersion_algorithmTypeId,algorithmTypeVersion_algorithmTypeVersionName,executorType_executorTypeId,executorType_guid,executorType_insertedRowDate,executorType_lastUpdatedDate,executorType_executorTypeName,executorType_executorTypeClass)
  }  
 def toStringArray() : Array[String] = {
    Array(""+algorithmImplementationId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+algorithmTypeVersionId,""+executorTypeId,""+algorithmImplementationName,""+algorithmImplementationClass,""+algorithmTypeVersion_algorithmTypeVersionId,""+algorithmTypeVersion_insertedRowDate,""+algorithmTypeVersion_lastUpdatedDate,""+algorithmTypeVersion_guid,""+algorithmTypeVersion_algorithmTypeId,""+algorithmTypeVersion_algorithmTypeVersionName,""+executorType_executorTypeId,""+executorType_guid,""+executorType_insertedRowDate,""+executorType_lastUpdatedDate,""+executorType_executorTypeName,""+executorType_executorTypeClass) 
  } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "algorithmImplementationId" => algorithmImplementationId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "algorithmTypeVersionId" => algorithmTypeVersionId  
     case "executorTypeId" => executorTypeId  
     case "algorithmImplementationName" => algorithmImplementationName  
     case "algorithmImplementationClass" => algorithmImplementationClass  
     case "algorithmTypeVersion_algorithmTypeVersionId" => algorithmTypeVersion_algorithmTypeVersionId  
     case "algorithmTypeVersion_insertedRowDate" => algorithmTypeVersion_insertedRowDate  
     case "algorithmTypeVersion_lastUpdatedDate" => algorithmTypeVersion_lastUpdatedDate  
     case "algorithmTypeVersion_guid" => algorithmTypeVersion_guid  
     case "algorithmTypeVersion_algorithmTypeId" => algorithmTypeVersion_algorithmTypeId  
     case "algorithmTypeVersion_algorithmTypeVersionName" => algorithmTypeVersion_algorithmTypeVersionName  
     case "executorType_executorTypeId" => executorType_executorTypeId  
     case "executorType_guid" => executorType_guid  
     case "executorType_insertedRowDate" => executorType_insertedRowDate  
     case "executorType_lastUpdatedDate" => executorType_lastUpdatedDate  
     case "executorType_executorTypeName" => executorType_executorTypeName  
     case "executorType_executorTypeClass" => executorType_executorTypeClass   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "algorithmImplementationId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "algorithmTypeVersionId" => "Long"  
     case "executorTypeId" => "Long"  
     case "algorithmImplementationName" => "String"  
     case "algorithmImplementationClass" => "String"  
     case "algorithmTypeVersion_algorithmTypeVersionId" => "Long"  
     case "algorithmTypeVersion_insertedRowDate" => "java.util.Date"  
     case "algorithmTypeVersion_lastUpdatedDate" => "java.util.Date"  
     case "algorithmTypeVersion_guid" => "Long"  
     case "algorithmTypeVersion_algorithmTypeId" => "Long"  
     case "algorithmTypeVersion_algorithmTypeVersionName" => "String"  
     case "executorType_executorTypeId" => "Long"  
     case "executorType_guid" => "Long"  
     case "executorType_insertedRowDate" => "java.util.Date"  
     case "executorType_lastUpdatedDate" => "java.util.Date"  
     case "executorType_executorTypeName" => "String"  
     case "executorType_executorTypeClass" => "String"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VAlgorithmImplementationDto { 
  val TABLE_NAME = "vAlgorithmImplementation"; 
   val FIELD_algorithmImplementationId = "algorithmImplementationId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_algorithmTypeVersionId = "algorithmTypeVersionId";
   val FIELD_executorTypeId = "executorTypeId";
   val FIELD_algorithmImplementationName = "algorithmImplementationName";
   val FIELD_algorithmImplementationClass = "algorithmImplementationClass";
   val FIELD_algorithmTypeVersion_algorithmTypeVersionId = "algorithmTypeVersion_algorithmTypeVersionId";
   val FIELD_algorithmTypeVersion_insertedRowDate = "algorithmTypeVersion_insertedRowDate";
   val FIELD_algorithmTypeVersion_lastUpdatedDate = "algorithmTypeVersion_lastUpdatedDate";
   val FIELD_algorithmTypeVersion_guid = "algorithmTypeVersion_guid";
   val FIELD_algorithmTypeVersion_algorithmTypeId = "algorithmTypeVersion_algorithmTypeId";
   val FIELD_algorithmTypeVersion_algorithmTypeVersionName = "algorithmTypeVersion_algorithmTypeVersionName";
   val FIELD_executorType_executorTypeId = "executorType_executorTypeId";
   val FIELD_executorType_guid = "executorType_guid";
   val FIELD_executorType_insertedRowDate = "executorType_insertedRowDate";
   val FIELD_executorType_lastUpdatedDate = "executorType_lastUpdatedDate";
   val FIELD_executorType_executorTypeName = "executorType_executorTypeName";
   val FIELD_executorType_executorTypeClass = "executorType_executorTypeClass";

}

 
