/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VExecutorStorageTypeSummaryDto ( 
     val executorStorageTypeId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val executorStorageTypeName : String
     , val executorStorageTypeClass : String
     , val algorithmStorageSupport_count : Int
     , val executorStorage_count : Int 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vExecutorStorageTypeSummary";    }  
   def fields : String = {    "executorStorageTypeId,guid,insertedRowDate,lastUpdatedDate,executorStorageTypeName,executorStorageTypeClass,algorithmStorageSupport_count,executorStorage_count";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    executorStorageTypeId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(executorStorageTypeId,guid,insertedRowDate,lastUpdatedDate,executorStorageTypeName,executorStorageTypeClass,algorithmStorageSupport_count,executorStorage_count)  }  
 def toStringArray() : Array[String] = {    Array(""+executorStorageTypeId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+executorStorageTypeName,""+executorStorageTypeClass,""+algorithmStorageSupport_count,""+executorStorage_count)   }  
 def toJson() : String = {   "{" + "\"executorStorageTypeId\":\""+executorStorageTypeId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"executorStorageTypeName\":\""+executorStorageTypeName+"\""+","+"\"executorStorageTypeClass\":\""+executorStorageTypeClass+"\""+","+"\"algorithmStorageSupport_count\":\""+algorithmStorageSupport_count+"\""+","+"\"executorStorage_count\":\""+executorStorage_count+"\"" + "}"   }  
 def toFullString() : String = {    "executorStorageTypeId:'"+executorStorageTypeId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"executorStorageTypeName:'"+executorStorageTypeName+"'"+","+"executorStorageTypeClass:'"+executorStorageTypeClass+"'"+","+"algorithmStorageSupport_count:'"+algorithmStorageSupport_count+"'"+","+"executorStorage_count:'"+executorStorage_count+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "executorStorageTypeId" => executorStorageTypeId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "executorStorageTypeName" => executorStorageTypeName  
     case "executorStorageTypeClass" => executorStorageTypeClass  
     case "algorithmStorageSupport_count" => algorithmStorageSupport_count  
     case "executorStorage_count" => executorStorage_count   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "executorStorageTypeId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "executorStorageTypeName" => "String"  
     case "executorStorageTypeClass" => "String"  
     case "algorithmStorageSupport_count" => "Int"  
     case "executorStorage_count" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VExecutorStorageTypeSummaryDto { 
  val TABLE_NAME = "vExecutorStorageTypeSummary"; 
   val FIELD_executorStorageTypeId = "executorStorageTypeId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_executorStorageTypeName = "executorStorageTypeName";
   val FIELD_executorStorageTypeClass = "executorStorageTypeClass";
   val FIELD_algorithmStorageSupport_count = "algorithmStorageSupport_count";
   val FIELD_executorStorage_count = "executorStorage_count";

}

 
