/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VExecutorStorageViewSummaryDto ( 
     val executorStorageViewId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val executorStorageSnapshotId : Long
     , val executorStorageId : Long
     , val sourceDownloadId : Long
     , val sourceViewId : Long
     , val storagePath : String
     , val viewSize : Long
     , val viewRowsCount : Long
     , val isValid : Int
     , val algorithmRunView_count : Int
     , val algorithmOutput_count : Int 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vExecutorStorageViewSummary";    }  
   def fields : String = {    "executorStorageViewId,guid,insertedRowDate,lastUpdatedDate,executorStorageSnapshotId,executorStorageId,sourceDownloadId,sourceViewId,storagePath,viewSize,viewRowsCount,isValid,algorithmRunView_count,algorithmOutput_count";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    executorStorageViewId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(executorStorageViewId,guid,insertedRowDate,lastUpdatedDate,executorStorageSnapshotId,executorStorageId,sourceDownloadId,sourceViewId,storagePath,viewSize,viewRowsCount,isValid,algorithmRunView_count,algorithmOutput_count)  }  
 def toStringArray() : Array[String] = {    Array(""+executorStorageViewId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+executorStorageSnapshotId,""+executorStorageId,""+sourceDownloadId,""+sourceViewId,""+storagePath,""+viewSize,""+viewRowsCount,""+isValid,""+algorithmRunView_count,""+algorithmOutput_count)   }  
 def toFullString() : String = {    "executorStorageViewId:'"+executorStorageViewId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"executorStorageSnapshotId:'"+executorStorageSnapshotId+"'"+","+"executorStorageId:'"+executorStorageId+"'"+","+"sourceDownloadId:'"+sourceDownloadId+"'"+","+"sourceViewId:'"+sourceViewId+"'"+","+"storagePath:'"+storagePath+"'"+","+"viewSize:'"+viewSize+"'"+","+"viewRowsCount:'"+viewRowsCount+"'"+","+"isValid:'"+isValid+"'"+","+"algorithmRunView_count:'"+algorithmRunView_count+"'"+","+"algorithmOutput_count:'"+algorithmOutput_count+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "executorStorageViewId" => executorStorageViewId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "executorStorageSnapshotId" => executorStorageSnapshotId  
     case "executorStorageId" => executorStorageId  
     case "sourceDownloadId" => sourceDownloadId  
     case "sourceViewId" => sourceViewId  
     case "storagePath" => storagePath  
     case "viewSize" => viewSize  
     case "viewRowsCount" => viewRowsCount  
     case "isValid" => isValid  
     case "algorithmRunView_count" => algorithmRunView_count  
     case "algorithmOutput_count" => algorithmOutput_count   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "executorStorageViewId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "executorStorageSnapshotId" => "Long"  
     case "executorStorageId" => "Long"  
     case "sourceDownloadId" => "Long"  
     case "sourceViewId" => "Long"  
     case "storagePath" => "String"  
     case "viewSize" => "Long"  
     case "viewRowsCount" => "Long"  
     case "isValid" => "Int"  
     case "algorithmRunView_count" => "Int"  
     case "algorithmOutput_count" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VExecutorStorageViewSummaryDto { 
  val TABLE_NAME = "vExecutorStorageViewSummary"; 
   val FIELD_executorStorageViewId = "executorStorageViewId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_executorStorageSnapshotId = "executorStorageSnapshotId";
   val FIELD_executorStorageId = "executorStorageId";
   val FIELD_sourceDownloadId = "sourceDownloadId";
   val FIELD_sourceViewId = "sourceViewId";
   val FIELD_storagePath = "storagePath";
   val FIELD_viewSize = "viewSize";
   val FIELD_viewRowsCount = "viewRowsCount";
   val FIELD_isValid = "isValid";
   val FIELD_algorithmRunView_count = "algorithmRunView_count";
   val FIELD_algorithmOutput_count = "algorithmOutput_count";

}

 
