/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VExecutorTypeHostParamDto ( 
     val executorTypeHostParamId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val executorHostId : Long
     , val executorTypeId : Long
     , val paramName : String
     , val paramValue : String
     , val executorHost_executorHostId : Long
     , val executorHost_guid : Long
     , val executorHost_insertedRowDate : java.util.Date
     , val executorHost_lastUpdatedDate : java.util.Date
     , val executorHost_hostName : String
     , val executorHost_hostIp : String
     , val executorHost_hostDomain : String
     , val executorHost_hostOsType : String
     , val executorHost_hostOsVersion : String
     , val executorHost_isWorking : Int
     , val executorType_executorTypeId : Long
     , val executorType_guid : Long
     , val executorType_insertedRowDate : java.util.Date
     , val executorType_lastUpdatedDate : java.util.Date
     , val executorType_executorTypeName : String
     , val executorType_executorTypeClass : String 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vExecutorTypeHostParam";    }  
   def fields : String = {    "executorTypeHostParamId,guid,insertedRowDate,lastUpdatedDate,executorHostId,executorTypeId,paramName,paramValue,executorHost_executorHostId,executorHost_guid,executorHost_insertedRowDate,executorHost_lastUpdatedDate,executorHost_hostName,executorHost_hostIp,executorHost_hostDomain,executorHost_hostOsType,executorHost_hostOsVersion,executorHost_isWorking,executorType_executorTypeId,executorType_guid,executorType_insertedRowDate,executorType_lastUpdatedDate,executorType_executorTypeName,executorType_executorTypeClass";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    executorTypeHostParamId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(executorTypeHostParamId,guid,insertedRowDate,lastUpdatedDate,executorHostId,executorTypeId,paramName,paramValue,executorHost_executorHostId,executorHost_guid,executorHost_insertedRowDate,executorHost_lastUpdatedDate,executorHost_hostName,executorHost_hostIp,executorHost_hostDomain,executorHost_hostOsType,executorHost_hostOsVersion,executorHost_isWorking,executorType_executorTypeId,executorType_guid,executorType_insertedRowDate,executorType_lastUpdatedDate,executorType_executorTypeName,executorType_executorTypeClass)  }  
 def toStringArray() : Array[String] = {    Array(""+executorTypeHostParamId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+executorHostId,""+executorTypeId,""+paramName,""+paramValue,""+executorHost_executorHostId,""+executorHost_guid,""+executorHost_insertedRowDate,""+executorHost_lastUpdatedDate,""+executorHost_hostName,""+executorHost_hostIp,""+executorHost_hostDomain,""+executorHost_hostOsType,""+executorHost_hostOsVersion,""+executorHost_isWorking,""+executorType_executorTypeId,""+executorType_guid,""+executorType_insertedRowDate,""+executorType_lastUpdatedDate,""+executorType_executorTypeName,""+executorType_executorTypeClass)   }  
 def toJson() : String = {   "{" + "\"executorTypeHostParamId\":\""+executorTypeHostParamId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"executorHostId\":\""+executorHostId+"\""+","+"\"executorTypeId\":\""+executorTypeId+"\""+","+"\"paramName\":\""+paramName+"\""+","+"\"paramValue\":\""+paramValue+"\""+","+"\"executorHost_executorHostId\":\""+executorHost_executorHostId+"\""+","+"\"executorHost_guid\":\""+executorHost_guid+"\""+","+"\"executorHost_insertedRowDate\":\""+executorHost_insertedRowDate+"\""+","+"\"executorHost_lastUpdatedDate\":\""+executorHost_lastUpdatedDate+"\""+","+"\"executorHost_hostName\":\""+executorHost_hostName+"\""+","+"\"executorHost_hostIp\":\""+executorHost_hostIp+"\""+","+"\"executorHost_hostDomain\":\""+executorHost_hostDomain+"\""+","+"\"executorHost_hostOsType\":\""+executorHost_hostOsType+"\""+","+"\"executorHost_hostOsVersion\":\""+executorHost_hostOsVersion+"\""+","+"\"executorHost_isWorking\":\""+executorHost_isWorking+"\""+","+"\"executorType_executorTypeId\":\""+executorType_executorTypeId+"\""+","+"\"executorType_guid\":\""+executorType_guid+"\""+","+"\"executorType_insertedRowDate\":\""+executorType_insertedRowDate+"\""+","+"\"executorType_lastUpdatedDate\":\""+executorType_lastUpdatedDate+"\""+","+"\"executorType_executorTypeName\":\""+executorType_executorTypeName+"\""+","+"\"executorType_executorTypeClass\":\""+executorType_executorTypeClass+"\"" + "}"   }  
 def toFullString() : String = {    "executorTypeHostParamId:'"+executorTypeHostParamId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"executorHostId:'"+executorHostId+"'"+","+"executorTypeId:'"+executorTypeId+"'"+","+"paramName:'"+paramName+"'"+","+"paramValue:'"+paramValue+"'"+","+"executorHost_executorHostId:'"+executorHost_executorHostId+"'"+","+"executorHost_guid:'"+executorHost_guid+"'"+","+"executorHost_insertedRowDate:'"+executorHost_insertedRowDate+"'"+","+"executorHost_lastUpdatedDate:'"+executorHost_lastUpdatedDate+"'"+","+"executorHost_hostName:'"+executorHost_hostName+"'"+","+"executorHost_hostIp:'"+executorHost_hostIp+"'"+","+"executorHost_hostDomain:'"+executorHost_hostDomain+"'"+","+"executorHost_hostOsType:'"+executorHost_hostOsType+"'"+","+"executorHost_hostOsVersion:'"+executorHost_hostOsVersion+"'"+","+"executorHost_isWorking:'"+executorHost_isWorking+"'"+","+"executorType_executorTypeId:'"+executorType_executorTypeId+"'"+","+"executorType_guid:'"+executorType_guid+"'"+","+"executorType_insertedRowDate:'"+executorType_insertedRowDate+"'"+","+"executorType_lastUpdatedDate:'"+executorType_lastUpdatedDate+"'"+","+"executorType_executorTypeName:'"+executorType_executorTypeName+"'"+","+"executorType_executorTypeClass:'"+executorType_executorTypeClass+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "executorTypeHostParamId" => executorTypeHostParamId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "executorHostId" => executorHostId  
     case "executorTypeId" => executorTypeId  
     case "paramName" => paramName  
     case "paramValue" => paramValue  
     case "executorHost_executorHostId" => executorHost_executorHostId  
     case "executorHost_guid" => executorHost_guid  
     case "executorHost_insertedRowDate" => executorHost_insertedRowDate  
     case "executorHost_lastUpdatedDate" => executorHost_lastUpdatedDate  
     case "executorHost_hostName" => executorHost_hostName  
     case "executorHost_hostIp" => executorHost_hostIp  
     case "executorHost_hostDomain" => executorHost_hostDomain  
     case "executorHost_hostOsType" => executorHost_hostOsType  
     case "executorHost_hostOsVersion" => executorHost_hostOsVersion  
     case "executorHost_isWorking" => executorHost_isWorking  
     case "executorType_executorTypeId" => executorType_executorTypeId  
     case "executorType_guid" => executorType_guid  
     case "executorType_insertedRowDate" => executorType_insertedRowDate  
     case "executorType_lastUpdatedDate" => executorType_lastUpdatedDate  
     case "executorType_executorTypeName" => executorType_executorTypeName  
     case "executorType_executorTypeClass" => executorType_executorTypeClass   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "executorTypeHostParamId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "executorHostId" => "Long"  
     case "executorTypeId" => "Long"  
     case "paramName" => "String"  
     case "paramValue" => "String"  
     case "executorHost_executorHostId" => "Long"  
     case "executorHost_guid" => "Long"  
     case "executorHost_insertedRowDate" => "java.util.Date"  
     case "executorHost_lastUpdatedDate" => "java.util.Date"  
     case "executorHost_hostName" => "String"  
     case "executorHost_hostIp" => "String"  
     case "executorHost_hostDomain" => "String"  
     case "executorHost_hostOsType" => "String"  
     case "executorHost_hostOsVersion" => "String"  
     case "executorHost_isWorking" => "Int"  
     case "executorType_executorTypeId" => "Long"  
     case "executorType_guid" => "Long"  
     case "executorType_insertedRowDate" => "java.util.Date"  
     case "executorType_lastUpdatedDate" => "java.util.Date"  
     case "executorType_executorTypeName" => "String"  
     case "executorType_executorTypeClass" => "String"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VExecutorTypeHostParamDto { 
  val TABLE_NAME = "vExecutorTypeHostParam"; 
   val FIELD_executorTypeHostParamId = "executorTypeHostParamId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_executorHostId = "executorHostId";
   val FIELD_executorTypeId = "executorTypeId";
   val FIELD_paramName = "paramName";
   val FIELD_paramValue = "paramValue";
   val FIELD_executorHost_executorHostId = "executorHost_executorHostId";
   val FIELD_executorHost_guid = "executorHost_guid";
   val FIELD_executorHost_insertedRowDate = "executorHost_insertedRowDate";
   val FIELD_executorHost_lastUpdatedDate = "executorHost_lastUpdatedDate";
   val FIELD_executorHost_hostName = "executorHost_hostName";
   val FIELD_executorHost_hostIp = "executorHost_hostIp";
   val FIELD_executorHost_hostDomain = "executorHost_hostDomain";
   val FIELD_executorHost_hostOsType = "executorHost_hostOsType";
   val FIELD_executorHost_hostOsVersion = "executorHost_hostOsVersion";
   val FIELD_executorHost_isWorking = "executorHost_isWorking";
   val FIELD_executorType_executorTypeId = "executorType_executorTypeId";
   val FIELD_executorType_guid = "executorType_guid";
   val FIELD_executorType_insertedRowDate = "executorType_insertedRowDate";
   val FIELD_executorType_lastUpdatedDate = "executorType_lastUpdatedDate";
   val FIELD_executorType_executorTypeName = "executorType_executorTypeName";
   val FIELD_executorType_executorTypeClass = "executorType_executorTypeClass";

}

 
