/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dao

import anorm.{SQL, SqlParser}
import com.mlasaf.dto._
import java.util.Date


 class VDownloadTransformGroupSummaryDao extends DaoBase { 

  def getVDownloadTransformGroupSummarysList() : List[VDownloadTransformGroupSummaryDto] = {
   implicit val connection = getConnection();
   val dtos : List[VDownloadTransformGroupSummaryDto]= SQL("select * from vDownloadTransformGroupSummary").as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);
   dtos
  }
  def getVDownloadTransformGroupSummarysCount() : Long = {
   implicit val connection = getConnection();
   val cnt : Long = SQL("select count(*) as cnt from vDownloadTransformGroupSummary").executeQuery()(connection).as[Long](SqlParser.long("cnt").single)(connection);;
   cnt
  }
  def getVDownloadTransformGroupSummarysLastInsertDate() : java.util.Date = {
   implicit val connection = getConnection();
   val ld : java.util.Date = SQL("select max(insertedRowDate) as lastDate from vDownloadTransformGroupSummary").executeQuery()(connection).as[java.util.Date](SqlParser.date("lastDate").single)(connection);;
   ld
  }
  def getVDownloadTransformGroupSummarysLastUpdatedDate() : java.util.Date = {
   implicit val connection = getConnection();
   val ld : java.util.Date = SQL("select max(lastUpdatedDate) as lastUpdatedDate from vDownloadTransformGroupSummary").executeQuery()(connection).as[java.util.Date](SqlParser.date("lastUpdatedDate").single)(connection);;
   ld
  }
  def getVDownloadTransformGroupSummaryFirst() : VDownloadTransformGroupSummaryDto = {
   implicit val connection = getConnection();
   val dtos : VDownloadTransformGroupSummaryDto= SQL("select * from vDownloadTransformGroupSummary order by insertedRowDate asc ").as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*).head;
   dtos
  }
  def getVDownloadTransformGroupSummaryLast() : VDownloadTransformGroupSummaryDto = {
   implicit val connection = getConnection();
   val dtos : VDownloadTransformGroupSummaryDto= SQL("select * from vDownloadTransformGroupSummary order by insertedRowDate desc ").as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*).head;
   dtos
  }
  def getVDownloadTransformGroupSummaryByGuid(guid : Long) : VDownloadTransformGroupSummaryDto = {
   implicit val connection = getConnection();
   val dtos : VDownloadTransformGroupSummaryDto= SQL("select * from vDownloadTransformGroupSummary where guid = {guid} ").on("guid" -> guid).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].single);
   dtos
  }  
 def getDtosByDownloadTransformGroupId(colValue : Long) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where downloadTransformGroupId = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByGuid(colValue : Long) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where guid = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByInsertedRowDate(colValue : java.util.Date) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where insertedRowDate = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByLastUpdatedDate(colValue : java.util.Date) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where lastUpdatedDate = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByDownloadTransformGroupName(colValue : String) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where downloadTransformGroupName = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByDownloadTransformExecutorStorage_count(colValue : Int) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where downloadTransformExecutorStorage_count = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByDownloadTransform_count(colValue : Int) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where downloadTransform_count = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  
 def getDtosByDownloadTransformAlgorithmSchedule_count(colValue : Int) : List[VDownloadTransformGroupSummaryDto] = { 
   implicit val connection = getConnection();  
   val dtos : List[VDownloadTransformGroupSummaryDto] = SQL("select * from vDownloadTransformGroupSummary where downloadTransformAlgorithmSchedule_count = {colValue} ").on("colValue" -> colValue).as(anorm.Macro.namedParser[VDownloadTransformGroupSummaryDto].*);  
   dtos  
 }  

} 
