/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto

import com.lucidchart.relate._
import java.util.Date


object Dtos {

}



























